Listing dashboard Implementation
CS320F21T3/hiring-hand pull request #43
Opened 2021-11-12 22:03 UTC by hugoamaralsantana

Created the front-end for the Listing Dashboard. It consists of a ListGroup that displays the Listing cards, the Filter Menu, the Full Listing Viewer, and the entire Listing Container that organizes the overall Listing Dashboard layout. 

There are most likely one or two scaling errors with my .scss files where maybe a large window might look slightly different to a small one with the card sizings. But it's a very minor, non-disruptive problem. We can fix it later on.

2021-11-12 22:20 UTC, benmelz requested changes
Quick lookthrough - the content itself looks great but a couple of bigger picture things to mention

- From my naked eye it looks to me like there are some linting offenses so if you haven't, `yarn run lint` and fix anything it complains about
- In terms of actual content for the PR you're missing some of the plug-in functionality I was trying (failing) to describe over slack. Specifically I meant stuff like replacing the "sample content" (`FullListing`, `ListingCard`) with proper interpolations from `props` (i.e. replace "This will be the snippet description..." with `{this.props.listing.description}`).

2021-11-12 22:20 UTC, benmelz commented on app/client/components/FilterMenu.jsx
> +export default withRemote(withSession(withRoutes(withRouter(FilterMenu)))
I'm guessing this is a copy from other files - you actually don't need these here. They're actually composition hooks that make "global" properties available within the component tree (i.e. `withRemote` exposes the remote instance contained in `App` available as `this.props.remote` here). So, if you don't need to use them within the component the composition isn't necessary.

```suggestion
export default FilterMenu
```

2021-11-12 22:20 UTC, benmelz commented on app/client/components/FilterMenu.module.scss
> +}
As a forewarning, it seems to me that most (if not all) of this css module and the other one can be replaced with bootstrap features - I can go over it with you sometime soon

2021-11-12 22:20 UTC, benmelz commented on app/client/components/FullListing.jsx
> +      </div>
I'm not sure if eslint will pick this up, but indentation here is a little wonky

2021-11-12 22:20 UTC, benmelz commented on app/client/components/FullListing.module.scss
> +}
`\n` missing at end of the file (eslint will automatically fix this for you i think)

2021-11-13 15:31 UTC, hugoamaralsantana commented on app/client/components/FullListing.jsx
> +      </div>
Yeah, my bad about that. I forgot to run eslint before the push.

2021-11-13 15:32 UTC, hugoamaralsantana commented on app/client/components/FilterMenu.module.scss
> +}
Bet, hmu on Slack

2021-11-13 16:02 UTC, hugoamaralsantana commented on app/client/components/FullListing.module.scss
> +}
My bad on the eslint stuff. I'll get it touched up as soon as possible.

2021-11-13 22:32 UTC, benmelz requested changes
More big-picture comments:

`FilterMenu`:
  - could exist as private component in `ListingBrowser` since definitely only used there
  - dropdown functionality should exist in `ListingBrowser`, thinking modularly a `Menu` should contain only the menu itself and not any wrapping (leave it up to the parent how to display it).
  - can probably omit actual sorting buttons yet (not well defined by team what sorting features we plan to implement ?)

`FullListing`:
  - rename => `Listing`
  - close functionality should exist in `ListingBrowser`, thinking modularly a "Display" component should only contain display functionality for data (leave it up to the parent how to show/hide).
  - use attributes from `this.props.listing` rather than sample text

`ListingCard`:
  - rename => `ListingItem`
  - could exist as private component in `ListingBrowser` since (should be?) only used there
  - use attributes from `this.props.listing` rather than sample text

`ListingContainer`:
  - rename => ListingBrowser
  - copy `this.props.listings` to `this.state.listings` (for filtering/sorting functionality)
  - use `this.state.listings` to generate `ListingItem` (iterative component generation, make sure to set ids, ask if unsure how)

Overall I actually would say to actually hold off on adding responsive features (click listeners etc) - PR is big/complex enough as it is

2021-11-17 22:34 UTC, merged